version: "3"
services:
  postgres:
    image: postgres:10.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  prometheus:
    image: prom/prometheus:v2.1.0
    restart: always
    command:
      - "--config.file=/prometheus-data/prometheus.yml"
      # Uncomment to enable the Admin API
      - "--web.enable-admin-api"
      # Uncomment to determine when to remove old data. Prometheus defaults to keeping data for 15 days.
      - "--storage.tsdb.retention=1d"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-data:/prometheus-data"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - "3000:3000"
