{
 "title": "Application metrics",
 "description": "Application metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored[5m])) / sum(increase(graphql_queries_responded[5m]))"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_total_request_time_bucket[5m])) by (service, operationName, operation) * 60",
     "legendFormat": "{{operation}} - {{operationName}}"
    }
   ]
  },
  {
   "title": "Resolver Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_resolver_time_bucket[5m])) by (service, parentType, fieldName, returnType) * 60",
     "legendFormat": "{{parentType}} - {{fieldName}} : {{returnType}}"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(graphql_total_request_time_bucket[5m])) by (le, operationName, operation))",
     "legendFormat": "{{operation}} - {{operationName}}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(graphql_total_request_time_bucket[5m])) by (le, operationName, operation))",
     "legendFormat": "{{operation}} - {{operationName}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1024) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}