scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:4000"]
        labels:
          service: "prisma"
          group: "production"
rule_files:
  - "alert.rules"
